name: build_and_publish_testpypi

on: workflow_dispatch

jobs:
  build_packages:
    name: Building wheels and main package
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        poetry-version: [1.8]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip and poetry ${{ matrix.poetry-version }}
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==${{ matrix.poetry-version }}


    - name: Build with Poetry
      shell: bash
      run: |
        python -m poetry build

    - name: Install dependencies
      shell: bash
      run: python -m poetry install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: poetry-dist-objects-${{ matrix.os }}
        path: |
          dist/*.whl
          dist/*.tar.gz
          dist/*.zip

  pypipublish:
    needs: build_packages
    name: Publish to PyPI
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
        poetry-version: [1.8]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Download all build objects (artifacts)
      uses: actions/download-artifact@v3

    - name: Extract files
      run: |
        ls -R
        mkdir dist
        mv poetry-dist-objects-macos-latest/*.whl dist/
        mv poetry-dist-objects-windows-latest/*.whl dist/
        mv poetry-dist-objects-ubuntu-latest/* dist/

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
